services:

  database:
    container_name: 'database'
    image: 'bitnami/mysql:latest'
    cpus: 2
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_USER=admin
      - MYSQL_DATABASE=hyperativa
      - MYSQL_PASSWORD=qjXy9VDs8Cz4r5emEhubWF7g
      - MYSQL_ROOT_PASSWORD=czsun6MSWFD2Zxf4AXgbN53KC7HUjhpQ8awR
    ports:
      - '0.0.0.0:3306:3306'


#  app:
#    container_name: "app"
#    build:
#      context: ..
#      dockerfile: Dockerfile
#    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main.app:asgi_app --bind 0.0.0.0:8000
#    ports:
#      - "0.0.0.0:8000:8000"
#    depends_on:
#      - database
