### POST request to server and create a credit card register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzAwMTkzOCwianRpIjoiZGUxMjU2ZjktMzY0ZC00YTk0LWI0ZDUtZGZlNGMyYjViNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNwZXJyeSIsIm5iZiI6MTcyMzAwMTkzOCwiY3NyZiI6IjRhNGY5MGFjLWE0M2ItNGJmZC04ZGM3LTc1ZGNkMjVkZGU5NyIsImV4cCI6MTcyMzAwMzczOH0.Eo1Jtpg7W31HBPYI4FAak3nOgozmkVWSwLM3UVQJ31g

--boundary
Content-Disposition: form-data; name="flat_data"; filename="flat_data.txt"

< ../../file_ingestion/flat_data.txt

