### POST request to server and create a credit card register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4


--boundary
Content-Disposition: form-data; name="flat_data"; filename="flat_data.txt"

< ../../file_ingestion/flat_data.txt


###