### POST request to server and create a credit card register


### First Register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzAwMTkzOCwianRpIjoiZGUxMjU2ZjktMzY0ZC00YTk0LWI0ZDUtZGZlNGMyYjViNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNwZXJyeSIsIm5iZiI6MTcyMzAwMTkzOCwiY3NyZiI6IjRhNGY5MGFjLWE0M2ItNGJmZC04ZGM3LTc1ZGNkMjVkZGU5NyIsImV4cCI6MTcyMzAwMzczOH0.Eo1Jtpg7W31HBPYI4FAak3nOgozmkVWSwLM3UVQJ31g

{
    "name": "Paulo F. Pacheco",
    "date": "20240728",
    "batch_name": "LOTE0001",
    "registers": 1,
    "line": 1,
    "batch_number": 1,
    "credit_card_number": "4456897922969999"
}


### Second Register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzAwMTkzOCwianRpIjoiZGUxMjU2ZjktMzY0ZC00YTk0LWI0ZDUtZGZlNGMyYjViNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNwZXJyeSIsIm5iZiI6MTcyMzAwMTkzOCwiY3NyZiI6IjRhNGY5MGFjLWE0M2ItNGJmZC04ZGM3LTc1ZGNkMjVkZGU5NyIsImV4cCI6MTcyMzAwMzczOH0.Eo1Jtpg7W31HBPYI4FAak3nOgozmkVWSwLM3UVQJ31g

{
    "name": "Douglas Terci",
    "date": "20240725",
    "batch_name": "LOTE0002",
    "registers": 1,
    "line": 1,
    "batch_number": 1,
    "credit_card_number": "4456897922968888"
}

### Third Register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzAwMTkzOCwianRpIjoiZGUxMjU2ZjktMzY0ZC00YTk0LWI0ZDUtZGZlNGMyYjViNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNwZXJyeSIsIm5iZiI6MTcyMzAwMTkzOCwiY3NyZiI6IjRhNGY5MGFjLWE0M2ItNGJmZC04ZGM3LTc1ZGNkMjVkZGU5NyIsImV4cCI6MTcyMzAwMzczOH0.Eo1Jtpg7W31HBPYI4FAak3nOgozmkVWSwLM3UVQJ31g

{
    "name": "Kolemman Schulemann ",
    "date": "20240725",
    "batch_name": "LOTE0003",
    "registers": 1,
    "line": 1,
    "batch_number": 1,
    "credit_card_number": "5156897922963333"
}

### Fourth Register

POST http://localhost:8000/rest/api/v1/credit_card
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzAwMTkzOCwianRpIjoiZGUxMjU2ZjktMzY0ZC00YTk0LWI0ZDUtZGZlNGMyYjViNTM2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InNwZXJyeSIsIm5iZiI6MTcyMzAwMTkzOCwiY3NyZiI6IjRhNGY5MGFjLWE0M2ItNGJmZC04ZGM3LTc1ZGNkMjVkZGU5NyIsImV4cCI6MTcyMzAwMzczOH0.Eo1Jtpg7W31HBPYI4FAak3nOgozmkVWSwLM3UVQJ31g

{
    "name": "Andy Warhol ",
    "date": "20240725",
    "batch_name": "LOTE0035",
    "registers": 1,
    "line": 1,
    "batch_number": 1,
    "credit_card_number": "5555897922963331"
}