### POST request to server

### First User

## Already Created

### Second User

POST http://localhost:5000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI4MTY3NiwianRpIjoiMTIwYzBiNWQtYzkwMy00Mjk2LWEwM2MtNGI5OTY4NmYzYWU4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjgxNjc2LCJjc3JmIjoiYmM4ZmY4ZTctNTExOC00YzkyLTkxMDQtNjRhOTI1NmUxMzhkIiwiZXhwIjoxNzIyMjgzNDc2fQ.CHe-Af9T1AGp3SHcfdGtOrVdyMFDFzdh_s9jlbyGehQ


{
    "name": "Steve Perry",
    "is_active": "True",
    "username": "sperry",
    "password": "$dA)yp6(",
    "password_confirmation": "$dA)yp6("
}

### Third User

POST http://localhost:5000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI4MTY3NiwianRpIjoiMTIwYzBiNWQtYzkwMy00Mjk2LWEwM2MtNGI5OTY4NmYzYWU4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjgxNjc2LCJjc3JmIjoiYmM4ZmY4ZTctNTExOC00YzkyLTkxMDQtNjRhOTI1NmUxMzhkIiwiZXhwIjoxNzIyMjgzNDc2fQ.CHe-Af9T1AGp3SHcfdGtOrVdyMFDFzdh_s9jlbyGehQ

{
    "name": "Tony Morello",
    "is_active": "True",
    "username": "tmorello",
    "password": "g%&#$94!",
    "password_confirmation": "g%&#$94!"
}