### POST request to server

### First User

## Already Created

### Second User

POST http://localhost:8000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjcxODQ4MCwianRpIjoiNDM0MDJkMjEtYjViZS00OTg2LWJlMTUtNjViODM1NjExYTNhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyNzE4NDgwLCJjc3JmIjoiOWRlNjEzOWYtN2NiNC00Mjg5LTg4NDAtY2RmZjA2NzljYzkyIiwiZXhwIjoxNzIyNzIwMjgwfQ.a-pbQq2TyX-YlsXTKElkn6yfVO3rA4GI1Dq54y_g0EI

{
    "name": "Steve Perry",
    "is_active": "True",
    "username": "sperry",
    "password": "$dA)yp6(",
    "password_confirmation": "$dA)yp6("
}

### Third User

POST http://localhost:8000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjcxODQ4MCwianRpIjoiNDM0MDJkMjEtYjViZS00OTg2LWJlMTUtNjViODM1NjExYTNhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyNzE4NDgwLCJjc3JmIjoiOWRlNjEzOWYtN2NiNC00Mjg5LTg4NDAtY2RmZjA2NzljYzkyIiwiZXhwIjoxNzIyNzIwMjgwfQ.a-pbQq2TyX-YlsXTKElkn6yfVO3rA4GI1Dq54y_g0EI

{
    "name": "Tony Morello",
    "is_active": "True",
    "username": "tmorello",
    "password": "g%&#$94!",
    "password_confirmation": "g%&#$94!"
}