### POST request to server

### First User

## Already Created

### Second User

POST http://localhost:8000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4


{
    "name": "Steve Perry",
    "is_active": "True",
    "username": "sperry",
    "password": "$dA)yp6(",
    "password_confirmation": "$dA)yp6("
}

### Third User

POST http://localhost:8000/rest/api/v1/create_user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4

{
    "name": "Tony Morello",
    "is_active": "True",
    "username": "tmorello",
    "password": "g%&#$94!",
    "password_confirmation": "g%&#$94!"
}