### GET request to example server

GET http://localhost:8000/rest/api/v1/credit_card/4456897922968888
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4


###

GET http://localhost:8000/rest/api/v1/credit_card/5217499906639580
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4


###

GET http://localhost:8000/rest/api/v1/credit_card/5156897922963333
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjI5MDcyNywianRpIjoiZDVhYTBhODUtMWI4My00OTQwLWI3ZjEtMGZjYzk2OGYyMTI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJzYW1ib3JhIiwibmJmIjoxNzIyMjkwNzI3LCJjc3JmIjoiZmEzOTJhZmMtZTliZS00NjlhLTg2MTItZjFhYzFjYTUzNWUyIiwiZXhwIjoxNzIyMjkyNTI3fQ.Cn6ATA7WNZXByLsTqbIVgH7leYZOXAChwrF4-xbD2C4
